name: Build Docker images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Github Docker registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: robinj1995/coronatracker/coronatracker
        registry: ghcr.io
        username: RobinJ1995
        password: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        snapshot: true
